import "./global.css";
import { Metadata } from "next";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Welcome to Superb Owl",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div suppressHydrationWarning>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
