import { CalEvent } from '@xulf/ui/shavon-lloyd';

export const EVENTS: CalEvent[] = [
  {
    id: '2',
    title: 'Luther - In a Grove',
    start: '2025-05-28',
    end: '2025-05-29',
    location: 'Ferndell Pavilion, Saratoga State Park',
    notes: 'By Chris Cerrone and Stephanie Fleischmann',
    href: 'https://www.operasaratoga.org/inagrove',
  },
  {
    id: '3',
    title: 'Kodály - She Loves Me',
    start: '2025-06-21',
    end: '2025-06-29',
    location: 'Universal Preservation Hall, Saratoga Springs, NY',
    notes: 'By Jerry Bock, Sheldon Harnick, and Masteroff',
    href: 'https://www.operasaratoga.org/shelovesme',
  },
  {
    id: '4',
    title: 'The 2025 Harlem Opera Festival',
    start: '2025-07-19T19:00:00',
    location: 'Richard Rodgers Amphitheater - Marcus Garvey Park',
    notes: 'Baritone soloist, HarlemPresents…',
    href: 'https://twi-ny.com/2025/07/25/harlem-presents-opera-ebony-marcus-garvey-park/',
  },
  {
    id: '5',
    title: 'The 2025 Harlem Musical Theater Festival',
    start: '2025-09-07T19:30:00',
    location: 'The Bandshell at Jackie Robinson Park, 319 W 145th Street',
    notes: 'Baritone soloist, HarlemPresents…',
    href: 'https://www.eventbrite.com/e/the-harlem-musical-theater-festival-2025-registration-1647558795709?aff=oddtdtcreator',
  },
  {
    id: '6',
    title: 'World Premiere: Songs for the People',
    start: '2025-11-22',
    location: 'Churchville-Chili High School, 5786 Buffalo Rd, Churchville, NY 14428',
    notes: 'SATB choir and piano, NYSSMA Zone 2 Area All-State Mixed Chorus, Holden Maiorana conductor',
  },
  {
    id: '7',
    title: 'A Christmas Tapestry: Bach, Britten, Bonds',
    start: '2025-12-06T14:30:00',
    end: '2025-12-07T17:30:00',
    location: 'Christ Church Greenwich, 254 E Putnam Ave, Greenwich, CT 06830',
    notes: 'Baritone soloist in Ballad of the Brown King (Bonds) and Christen ätzen diesen Tag, BWV 63 (Bach)',
    href: 'https://www.gcs-ct.org/202',
  },
  {
    id: '8',
    title: 'The Light Within – Winter Showcase Concert',
    start: '2025-12-15T19:00:00',
    location: 'First Presbyterian Church, 12 W 12th St, New York, NY 10011',
    notes: 'Conductor, National Children’s Chorus Premier and Scholars Ensembles',
    href: 'https://nationalchildrenschorus.com/event/winter-showcase-ny/',
  },
  {
    id: '9',
    title: 'Crispus Attucks – Cantori New York',
    start: '2026-03-13T20:00:00',
    end: '2026-03-14T20:00:00',
    location: 'Church of the Holy Apostles, 296 9th Ave.',
    notes: 'Baritone soloist, Adolphus Hailstork, Mark Shapiro conductor',
    href: 'https://app.arts-people.com/index.php?show=298415',
  },
  {
    id: '10',
    title: 'Mass in Time of War & Mass in Exile',
    start: '2026-04-17T20:00:00',
    location: 'Carnegie Hall, Stern Auditorium / Perelman Stage, NYC',
    notes: 'Baritone soloist, Cecilia Chorus NY, Mark Shapiro conductor',
    href: 'https://www.ceciliachorusny.org/brahms-and-hailstork',
  },
  {
    id: '11',
    title: 'Taking Flight – National Children’s Chorus',
    start: '2025-05-02T14:00:00',
    location: 'Carnegie Hall, Stern Auditorium / Perelman Stage, NYC',
    notes: 'Conductor, Premier and Scholars Ensembles',
    href: 'https://nationalchildrenschorus.com/event/taking-flight/',
  },
  {
    id: '12',
    title: 'Spring Showcase – Taking Flight',
    start: '2025-05-09T19:00:00',
    location: 'First Presbyterian Church, 12 W 12th St, New York, NY 10011',
    notes: 'Conductor, National Children’s Chorus Premier and Scholars Ensembles',
    href: 'https://nationalchildrenschorus.com/event/spring-showcase-ny/',
  },
];
