import { Work } from '@xulf/ui/shavon-lloyd';

export const CHORAL_WORKS: Work[] = [
  {
    id: '1',
    title: 'So Breaks the Sun',
    role: 'Composer',
    ensemble: 'SATB choir a cappella',
    details: '',
    year: null,
    youtubeId: 'mByX1j6gRII',
    category: 'Choral',
  },
  {
    id: '2',
    title: 'Alleluia',
    role: 'Composer',
    ensemble: 'SATB double choir, a cappella',
    details: '',
    year: null,
    youtubeId: 'VIq1-w4SaGY',
    category: 'Choral',
  },
  {
    id: '3',
    title: 'Tell Me',
    role: 'Composer',
    ensemble: 'SATB choir and oboe',
    details: '',
    year: null,
    youtubeId: 'igSnKmXEaLw',
    category: 'Choral',
  },
  {
    id: '4',
    title: 'Goodbye, My Friend (Peace and Love)',
    role: 'Composer',
    ensemble: 'SATB choir and piano',
    details: '',
    year: null,
    youtubeId: 'o-l-Pla-nrk',
    category: 'Choral',
  },
  {
    id: '5',
    title: 'Motherless Child',
    role: 'Composer',
    ensemble: 'SATB choir, piano, and tenor saxophone',
    details: '',
    year: null,
    youtubeId: '7E2Ur9RGwv8',
    category: 'Choral',
  },
  {
    id: '6',
    title: 'The Night Before Christmas',
    role: 'Composer',
    ensemble: 'SATB choir and orchestra',
    details: '',
    year: null,
    youtubeId: '27UK6IdtbTM',
    category: 'Choral',
  },
];