import { Work } from '@xulf/ui/shavon-lloyd';

export const CHORAL_WORKS: Work[] = [
  {
    id: '1',
    title: 'Goodbye, My Friend (Peace and Love)',
    role: 'Composer',
    ensemble: 'SATB choir and piano',
    details: '2021',
    year: 2021,
    youtubeId: '',
    category: 'Choral',
  },
  {
    id: '2',
    title: "8'46\": In Reflection of the Murder of George Floyd",
    role: 'Composer',
    ensemble: 'SATB choir a cappella',
    details: '2020',
    year: 2020,
    youtubeId: '',
    category: 'Choral',
  },
  {
    id: '3',
    title: 'Alleluia',
    role: 'Composer',
    ensemble: 'SATB double choir a cappella',
    details: '2019',
    year: 2019,
    youtubeId: 'WwRjPP-ANzs',
    category: 'Choral',
  },
  {
    id: '4',
    title: 'Motherless Child',
    role: 'Composer',
    ensemble: 'SATB choir, piano, and tenor saxophone',
    details: '2018',
    year: 2018,
    youtubeId: '',
    category: 'Choral',
  },
  {
    id: '5',
    title: 'So Breaks the Sun',
    role: 'Composer',
    ensemble: 'SATB choir a cappella',
    details: '2017',
    year: 2017,
    youtubeId: '',
    category: 'Choral',
  },
];

export const INSTRUMENTAL_WORKS: Work[] = [
  {
    id: '1',
    title: 'Solo for Contrabassoon',
    role: 'Composer',
    ensemble: 'Contrabassoon solo',
    details: '2018',
    year: 2018,
    youtubeId: '',
    category: 'Instrumental',
  },
  {
    id: '2',
    title: 'Tambora',
    role: 'Composer',
    ensemble: 'Brass quintet',
    details: '2018',
    year: 2018,
    youtubeId: '',
    category: 'Instrumental',
  },
  {
    id: '3',
    title: 'Continuum',
    role: 'Composer',
    ensemble: 'Alto saxophone and clarinet',
    details: '2017',
    year: 2017,
    youtubeId: '',
    category: 'Instrumental',
  },
  {
    id: '4',
    title: 'Bedlam',
    role: 'Composer',
    ensemble: 'Clarinet, alto saxophone, and bassoon',
    details: '2016',
    year: 2016,
    youtubeId: '',
    category: 'Instrumental',
  },
];