import './global.css';
import { StyledComponentsRegistry } from './registry';
import { SessionWrapper } from './session-wrapper';

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <SessionWrapper>{children}</SessionWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
