import './global.css';
import { StyledComponentsRegistry } from './registry';
import { SessionWrapper } from './session-wrapper';
import { DndProvider } from './components/editor/drag/DndProvider';

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <SessionWrapper>
            {/* <DndProvider> */}
              {children}
            {/* </DndProvider> */}
          </SessionWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
